const data = {
    arms: [
        "Bicep curl",
        "Arm day",
        "Tricep dips",
        "Hammer curl",
        "Overhead Triceps Extension",
        "Push-down",
        "Lying triceps extension",
        "Overhead press",
        "Tricep dumbbell kickback",
        "Close grip bench press",
        "Diamond push up",
        "Alternating renegade row",
        "Tate press",
        "Dip",
        "Side laterals to front raise",
        "Push-up",
        "EZ bar preacher curl",
        "One-arm dumbbell row",
        "Side lateral raise",
        "Pull-up",
        "Concentration curls",
        "Incline dumbbell curl",
        "Close grip push up",
        "Overhead cable curl",
        "Reverse barbell curl",
        "Cable rope overhead triceps extension",
        "Behind-the-back cable curl",
        "Dumbbell Flyes",
        "Weighted bench dip",
        "Cross body hammer curl",
        "Ez-bar curl",
        "Arm stretch",
        "Underhand kickback",
        "Rear delt raise",
        "Decline dumbbell triceps extension",
        "Dumbbell incline row",
        "Wide-grip standing barbell curl",
        "Dumbbell clean",
        "Lateral raise - with bands",
        "Poundstone curls",
        "Seated Wrist Curl",
        "Skull crusher",
        "One arm dumbbell preacher curl",
        "Wide curl",
        "Cable one arm tricep extension",
        "Incline hammer curls",
        "Palms-down wrist curl over a bench",
        "Standing overhead barbell triceps extension",
        "Javelin press",
        "Resistance band bicep curl",
        "Bench press",
        ],
    back: [
        "One-arm dumbbell row",
        "Pull-up",
        "Row",
        "Bent-over row",
        "Deadlift",
        "Roman Chair Back Extension",
        "Seated cable rows",
        "Alternating renegade row",
        "Pull-down",
        "Barbell deadlift",
        "Reverse flye",
        "Dumbbell pullover",
        "Wide-grip pull-up",
        "Inverted row",
        "Weighted pull ups",
        "Good-morning",
        "Dumbbell incline row",
        "Yates row",
        "Smith machine bent over row",
        "Meadows row",
        "Kettlebell swing",
        "Trap bar deadlift",
        "Farmer's walk",
        "Romanian deadlift with dumbbells",
        "Single-arm landmine row",
        "Ball leg curl",
        "Lying lateral raise",
        "Hang clean",
        "Band pull apart",
        "Pendlay Row",
        "Cable pullover",
        "Pallof press",
        "Burpee",
        "Dead row",
        "Upright barbell row",
        "Wide-grip lat pulldown",
        "Bent over two-dumbbell row with palms in",
        "Gorilla Row",
        "Straight-arm pulldown",
        "T-bar row",
        "T-bar row with handle",
        "Rack Pulls",
        "Rack pulls",
        "TRX row",
        "Squat",
        "Upright row",
        "Cat Cow",
        "Dumbbell shrug",
        "Medicine ball rotational throw",
        "Kettlebell windmill",
        "Barbell back squat",
    ],
    core: [
        "Plank",
        "Crunch",
        "Dead bug",
        "Bicycle crunch",
        "Bird dog exercise",
        "Bridge",
        "Russian twist",
        "Bear crawl",
        "Sit-up",
        "Leg raise",
        "Push-up",
        "Plank jack",
        "V-sit",
        "Kettlebell turkish get-up lunge style",
        "Side Plank",
        "Dragon flags",
        "Inchworm",
        "Forearm plank",
        "Glute bridge",
        "Rotational exercises",
        "Plank rotation",
        "Standing cable wood chop",
        "Hollow body hold",
        "Hanging leg raise",
        "Landmine rotation",
        "Mountain Climbers",
        "Flutter kick",
        "Supine Toe Tap",
        "Spiderman plank",
        "High boat to low boat",
        "Swiss ball rollout",
        "Seated knee tucks",
        "Modified plank",
        "Butterfly sit up",
        "Glute bridge march",
        "Oblique crunch",
        "Leg lower",
        "Rolling like a ball",
        "Jack knife crunch",
        "Vertical leg crunch",
        "Elbow to knee",
        "Hollow hold",
        "Shoulder tap",
        "Superman",
        "Reverse crunch",
        "Cable crunch",
        "Heel taps",
        "Kettlebell goblet squat",
        "Incline Mountain Climbers",
        "One arm dumbbell press",
        "Cross-body mountain climber",
    ],
    legs: [
        "Goblet squat",
        "Lunge",
        "Split squat",
        "Leg curl",
        "Leg press",
        "Romanian deadlift",
        "Calf raises",
        "Reverse lunge",
        "deadlift",
        "Calf raise",
        "Leg extension",
        "Hack squat",
        "Single leg deadlift",
        "Back squat",
        "Front squat",
        "Hip thrust",
        "Glute bridge",
        "Good-morning",
        "Cyclist squat",
        "Box jumps",
        "Kettlebell swing",
        "Barbell back squat",
        "Barbell reverse lunge",
        "Step ups",
    ],
    shoulders: [
        "Overhead press",
        "Side lateral raise",
        "Front raise",
        "Face pull",
        "Reverse flye",
        "Cable lateral raise",
        "External rotation",
        "Push press",
        "Clean and press",
        "Seated dumbbell press",
        "Upright row",
        "Z press",
        "Behind the neck press",
        "Dumbbell push press",
        "Dumbbell shoulder press",
        "Smith machine overhead shoulder press",
        "Cheat lateral",
        "Standing dumbbell upright row",
        "Front cable raise",
        "Seated barbell military press",
        "Barbell front raise",
        "Alternating kettlebell press",
        "Rear delt raise",
        "Barbell shoulder press",
        "Bent-over lateral raise",
        "Bench press",
        "High pull",
        "Dumbbell Flyes",
        "Push-up",
        "Upright barbell row",
        "Smith machine upright row",
        "Cable reverse fly",
        "Reverse machine flyes",
        "Upright cable row",
        "Y Raise",
        "Dumbbell One-Arm Shoulder Press",
        "Lateral raise - with bands",
        "Resistance band shoulder press",
        "Machine lateral raise",
        "Seated side lateral raise",
        "Standing military press",
        "Seated Arnold Press",
        "Neutral grip shoulder press",
        "Dumbbell rear delt row",
        "Arm Circles",
        "Band pull apart",
        "Front plate raise",
        "Kettlebell halo",
        "Half kneeling landmine press",
        "Lateral plank walk",
        "Inverted row",
    ],
    chest: [
        "Bench press",
        "Push-up",
        "Dumbbell Flyes",
        "Cable crossover",
        "Dumbbell bench press",
        "Incline dumbbell press",
        "Decline dumbbell bench press",
        "Parallel bar dip",
        "Fly",
        "Incline dumbbell fly",
        "Machine fly",
        "Dip",
        "Decline push-up",
        "Dumbbell pullover",
        "Low cable crossover",
        "Smith machine incline bench press",
        "Neck press",
        "Floor press",
        "Pullover",
        "Plyo push-up",
        "Machine bench press",
        "Wide pushup",
        "Close grip bench press",
        "Incline cable flye",
        "Plate press",
        "Barbell pullover",
        "Archer push up",
        "Clap push-up",
        "Close-grip dumbbell press",
        "Incline push-up",
        "Reverse grip bench press",
        "Squeeze press",
        "Single-arm cable crossover",
        "Alternating Dumbbell Bench Press",
        "Speed bench",
        "Prone fly",
        "Medicine ball push-up",
        "Wide grip dips",
        "Crossover push-up",
        "Cable iron cross",
        "Dynamic chest stretch",
        "Hammer grip incline db bench press",
        "Smith machine bench press",
        "Barbell bench press-wide grip",
        "Decline dumbbell flyes",
        "Cable chest press",
        "Dumbbell bench press with neutral grip",
        "One-arm dumbbell fly",
        "Kettlebell bench press",
        "Shoulder tap push-up",
        "Paused push up",
    ],
};


const data2 = {
    dates : ["21/07/2024","22/07/2024","23/07/2024","24/07/2024","25/07/2024"],
};

const data3 = {
    exerciseName: [
        "Bicep curl",
        "Arm day",
        "Tricep dips",
        "Hammer curl",
        "Overhead Triceps Extension",
        "Push-down",
        "Lying triceps extension",
        "Overhead press",
        "Tricep dumbbell kickback",
        "Close grip bench press",
        "Diamond push up",
        "Alternating renegade row",
        "Tate press",
        "Dip",
        "Side laterals to front raise",
        "Push-up",
        "EZ bar preacher curl",
        "One-arm dumbbell row",
        "Side lateral raise",
        "Pull-up",
        "Concentration curls",
        "Incline dumbbell curl",
        "Close grip push up",
        "Overhead cable curl",
        "Reverse barbell curl",
        "Cable rope overhead triceps extension",
        "Behind-the-back cable curl",
        "Dumbbell Flyes",
        "Weighted bench dip",
        "Cross body hammer curl",
        "Ez-bar curl",
        "Arm stretch",
        "Underhand kickback",
        "Rear delt raise",
        "Decline dumbbell triceps extension",
        "Dumbbell incline row",
        "Wide-grip standing barbell curl",
        "Dumbbell clean",
        "Lateral raise - with bands",
        "Poundstone curls",
        "Seated Wrist Curl",
        "Skull crusher",
        "One arm dumbbell preacher curl",
        "Wide curl",
        "Cable one arm tricep extension",
        "Incline hammer curls",
        "Palms-down wrist curl over a bench",
        "Standing overhead barbell triceps extension",
        "Javelin press",
        "Resistance band bicep curl",
        "Bench press",
        "One-arm dumbbell row",
        "Pull-up",
        "Row",
        "Bent-over row",
        "Deadlift",
        "Roman Chair Back Extension",
        "Seated cable rows",
        "Alternating renegade row",
        "Pull-down",
        "Barbell deadlift",
        "Reverse flye",
        "Dumbbell pullover",
        "Wide-grip pull-up",
        "Inverted row",
        "Weighted pull ups",
        "Good-morning",
        "Dumbbell incline row",
        "Yates row",
        "Smith machine bent over row",
        "Meadows row",
        "Kettlebell swing",
        "Trap bar deadlift",
        "Farmer's walk",
        "Romanian deadlift with dumbbells",
        "Single-arm landmine row",
        "Ball leg curl",
        "Lying lateral raise",
        "Hang clean",
        "Band pull apart",
        "Pendlay Row",
        "Cable pullover",
        "Pallof press",
        "Burpee",
        "Dead row",
        "Upright barbell row",
        "Wide-grip lat pulldown",
        "Bent over two-dumbbell row with palms in",
        "Gorilla Row",
        "Straight-arm pulldown",
        "T-bar row",
        "T-bar row with handle",
        "Rack Pulls",
        "Rack pulls",
        "TRX row",
        "Squat",
        "Upright row",
        "Cat Cow",
        "Dumbbell shrug",
        "Medicine ball rotational throw",
        "Kettlebell windmill",
        "Barbell back squat",
        "Plank",
        "Crunch",
        "Dead bug",
        "Bicycle crunch",
        "Bird dog exercise",
        "Bridge",
        "Russian twist",
        "Bear crawl",
        "Sit-up",
        "Leg raise",
        "Push-up",
        "Plank jack",
        "V-sit",
        "Kettlebell turkish get-up lunge style",
        "Side Plank",
        "Dragon flags",
        "Inchworm",
        "Forearm plank",
        "Glute bridge",
        "Rotational exercises",
        "Plank rotation",
        "Standing cable wood chop",
        "Hollow body hold",
        "Hanging leg raise",
        "Landmine rotation",
        "Mountain Climbers",
        "Flutter kick",
        "Supine Toe Tap",
        "Spiderman plank",
        "High boat to low boat",
        "Swiss ball rollout",
        "Seated knee tucks",
        "Modified plank",
        "Butterfly sit up",
        "Glute bridge march",
        "Oblique crunch",
        "Leg lower",
        "Rolling like a ball",
        "Jack knife crunch",
        "Vertical leg crunch",
        "Elbow to knee",
        "Hollow hold",
        "Shoulder tap",
        "Superman",
        "Reverse crunch",
        "Cable crunch",
        "Heel taps",
        "Kettlebell goblet squat",
        "Incline Mountain Climbers",
        "One arm dumbbell press",
        "Cross-body mountain climber",
        "Goblet squat",
        "Lunge",
        "Split squat",
        "Leg curl",
        "Leg press",
        "Romanian deadlift",
        "Calf raises",
        "Reverse lunge",
        "deadlift",
        "Calf raise",
        "Leg extension",
        "Hack squat",
        "Single leg deadlift",
        "Back squat",
        "Front squat",
        "Hip thrust",
        "Glute bridge",
        "Good-morning",
        "Cyclist squat",
        "Box jumps",
        "Kettlebell swing",
        "Barbell back squat",
        "Barbell reverse lunge",
        "Step ups",
        "Overhead press",
        "Side lateral raise",
        "Front raise",
        "Face pull",
        "Reverse flye",
        "Cable lateral raise",
        "External rotation",
        "Push press",
        "Clean and press",
        "Seated dumbbell press",
        "Upright row",
        "Z press",
        "Behind the neck press",
        "Dumbbell push press",
        "Dumbbell shoulder press",
        "Smith machine overhead shoulder press",
        "Cheat lateral",
        "Standing dumbbell upright row",
        "Front cable raise",
        "Seated barbell military press",
        "Barbell front raise",
        "Alternating kettlebell press",
        "Rear delt raise",
        "Barbell shoulder press",
        "Bent-over lateral raise",
        "Bench press",
        "High pull",
        "Dumbbell Flyes",
        "Push-up",
        "Upright barbell row",
        "Smith machine upright row",
        "Cable reverse fly",
        "Reverse machine flyes",
        "Upright cable row",
        "Y Raise",
        "Dumbbell One-Arm Shoulder Press",
        "Lateral raise - with bands",
        "Resistance band shoulder press",
        "Machine lateral raise",
        "Seated side lateral raise",
        "Standing military press",
        "Seated Arnold Press",
        "Neutral grip shoulder press",
        "Dumbbell rear delt row",
        "Arm Circles",
        "Band pull apart",
        "Front plate raise",
        "Kettlebell halo",
        "Half kneeling landmine press",
        "Lateral plank walk",
        "Inverted row",
        "Bench press",
        "Push-up",
        "Dumbbell Flyes",
        "Cable crossover",
        "Dumbbell bench press",
        "Incline dumbbell press",
        "Decline dumbbell bench press",
        "Parallel bar dip",
        "Fly",
        "Incline dumbbell fly",
        "Machine fly",
        "Dip",
        "Decline push-up",
        "Dumbbell pullover",
        "Low cable crossover",
        "Smith machine incline bench press",
        "Neck press",
        "Floor press",
        "Pullover",
        "Plyo push-up",
        "Machine bench press",
        "Wide pushup",
        "Close grip bench press",
        "Incline cable flye",
        "Plate press",
        "Barbell pullover",
        "Archer push up",
        "Clap push-up",
        "Close-grip dumbbell press",
        "Incline push-up",
        "Reverse grip bench press",
        "Squeeze press",
        "Single-arm cable crossover",
        "Alternating Dumbbell Bench Press",
        "Speed bench",
        "Prone fly",
        "Medicine ball push-up",
        "Wide grip dips",
        "Crossover push-up",
        "Cable iron cross",
        "Dynamic chest stretch",
        "Hammer grip incline db bench press",
        "Smith machine bench press",
        "Barbell bench press-wide grip",
        "Decline dumbbell flyes",
        "Cable chest press",
        "Dumbbell bench press with neutral grip",
        "One-arm dumbbell fly",
        "Kettlebell bench press",
        "Shoulder tap push-up",
        "Paused push up",
    ]
}

const data4 = {
    data: [
    {
        "date": "2024-07-27",
        "calories": 256,
    },
    {
        "date": "2024-07-28",
        "calories": 386,
    },
    {
        "date": "2024-07-29",
        "calories": 382,
    },
    {
        "date": "2024-07-30",
        "calories": 455,
    },
    {
        "date": "2024-07-31",
        "calories": 355,
    },
    {
        "date": "2024-08-01",
        "calories": 500,
    },
    {
        "date": "2024-08-02",
        "calories": 200,
    },
    {
        "date": "2024-08-03",
        "calories": 320,
    },
    ]
}

export {data, data2, data3, data4};
